const { TYPES } = require('./types');

const MOVE_CATEGORIES = {
  PHYSICAL: 'physical',
  SPECIAL: 'special',
  STATUS: 'status',
};

const MOVES = {
  tackle: {
    name: 'Tackle',
    type: TYPES.NORMAL,
    category: MOVE_CATEGORIES.PHYSICAL,
    power: 40,
    accuracy: 100,
    pp: 35,
    priority: 0,
    effects: [],
  },
  flamethrower: {
    name: 'Flamethrower',
    type: TYPES.FIRE,
    category: MOVE_CATEGORIES.SPECIAL,
    power: 90,
    accuracy: 100,
    pp: 15,
    priority: 0,
    effects: [{ type: 'status', status: 'burn', chance: 10, target: 'opponent' }],
  },
  thunderbolt: {
    name: 'Thunderbolt',
    type: TYPES.ELECTRIC,
    category: MOVE_CATEGORIES.SPECIAL,
    power: 90,
    accuracy: 100,
    pp: 15,
    priority: 0,
    effects: [{ type: 'status', status: 'paralysis', chance: 10, target: 'opponent' }],
  },
  iceBeam: {
    name: 'Ice Beam',
    type: TYPES.ICE,
    category: MOVE_CATEGORIES.SPECIAL,
    power: 90,
    accuracy: 100,
    pp: 10,
    priority: 0,
    effects: [{ type: 'status', status: 'freeze', chance: 10, target: 'opponent' }],
  },
  earthquake: {
    name: 'Earthquake',
    type: TYPES.GROUND,
    category: MOVE_CATEGORIES.PHYSICAL,
    power: 100,
    accuracy: 100,
    pp: 10,
    priority: 0,
    effects: [],
  },
  swordsDance: {
    name: 'Swords Dance',
    type: TYPES.NORMAL,
    category: MOVE_CATEGORIES.STATUS,
    power: 0,
    accuracy: null,
    pp: 20,
    priority: 0,
    effects: [{ type: 'stat', stat: 'attack', stages: 2, target: 'self' }],
  },
  willOWisp: {
    name: 'Will-O-Wisp',
    type: TYPES.FIRE,
    category: MOVE_CATEGORIES.STATUS,
    power: 0,
    accuracy: 85,
    pp: 15,
    priority: 0,
    effects: [{ type: 'status', status: 'burn', chance: 100, target: 'opponent' }],
  },
  quickAttack: {
    name: 'Quick Attack',
    type: TYPES.NORMAL,
    category: MOVE_CATEGORIES.PHYSICAL,
    power: 40,
    accuracy: 100,
    pp: 30,
    priority: 1,
    effects: [],
  },
  protect: {
    name: 'Protect',
    type: TYPES.NORMAL,
    category: MOVE_CATEGORIES.STATUS,
    power: 0,
    accuracy: null,
    pp: 10,
    priority: 4,
    effects: [{ type: 'protect', target: 'self' }],
  },
  toxicSpikes: {
    name: 'Toxic Spikes',
    type: TYPES.POISON,
    category: MOVE_CATEGORIES.STATUS,
    power: 0,
    accuracy: null,
    pp: 20,
    priority: 0,
    effects: [{ type: 'hazard', hazard: 'toxicSpikes', target: 'opponent' }],
  },
  stealthRock: {
    name: 'Stealth Rock',
    type: TYPES.ROCK,
    category: MOVE_CATEGORIES.STATUS,
    power: 0,
    accuracy: null,
    pp: 20,
    priority: 0,
    effects: [{ type: 'hazard', hazard: 'stealthRock', target: 'opponent' }],
  },
  recover: {
    name: 'Recover',
    type: TYPES.NORMAL,
    category: MOVE_CATEGORIES.STATUS,
    power: 0,
    accuracy: null,
    pp: 10,
    priority: 0,
    effects: [{ type: 'heal', amount: 0.5, target: 'self' }],
  },
  dragonClaw: {
    name: 'Dragon Claw',
    type: TYPES.DRAGON,
    category: MOVE_CATEGORIES.PHYSICAL,
    power: 80,
    accuracy: 100,
    pp: 15,
    priority: 0,
    effects: [],
  },
  shadowBall: {
    name: 'Shadow Ball',
    type: TYPES.GHOST,
    category: MOVE_CATEGORIES.SPECIAL,
    power: 80,
    accuracy: 100,
    pp: 15,
    priority: 0,
    effects: [{ type: 'stat', stat: 'specialDefense', stages: -1, chance: 20, target: 'opponent' }],
  },
  ironTail: {
    name: 'Iron Tail',
    type: TYPES.STEEL,
    category: MOVE_CATEGORIES.PHYSICAL,
    power: 100,
    accuracy: 75,
    pp: 15,
    priority: 0,
    effects: [{ type: 'stat', stat: 'defense', stages: -1, chance: 30, target: 'opponent' }],
  },
  surf: {
    name: 'Surf',
    type: TYPES.WATER,
    category: MOVE_CATEGORIES.SPECIAL,
    power: 90,
    accuracy: 100,
    pp: 15,
    priority: 0,
    effects: [],
  },
  leafBlade: {
    name: 'Leaf Blade',
    type: TYPES.GRASS,
    category: MOVE_CATEGORIES.PHYSICAL,
    power: 90,
    accuracy: 100,
    pp: 15,
    priority: 0,
    critRatio: 2,
    effects: [],
  },
  toxic: {
    name: 'Toxic',
    type: TYPES.POISON,
    category: MOVE_CATEGORIES.STATUS,
    power: 0,
    accuracy: 90,
    pp: 10,
    priority: 0,
    effects: [{ type: 'status', status: 'toxic', chance: 100, target: 'opponent' }],
  },
};

function getMoveById(id) {
  return MOVES[id] || null;
}

function validateMoveset(moves) {
  if (!Array.isArray(moves)) return false;
  if (moves.length === 0 || moves.length > 4) return false;
  const uniqueMoves = new Set(moves);
  return uniqueMoves.size === moves.length;
}

module.exports = { MOVES, MOVE_CATEGORIES, getMoveById, validateMoveset };
